'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class lang_ar
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("unblockDoom.lang_ar", GetType(lang_ar).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تم.
        '''</summary>
        Friend Shared ReadOnly Property all_done() As String
            Get
                Return ResourceManager.GetString("all_done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to متصل.
        '''</summary>
        Friend Shared ReadOnly Property connected() As String
            Get
                Return ResourceManager.GetString("connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جار الإتصال....
        '''</summary>
        Friend Shared ReadOnly Property connecting() As String
            Get
                Return ResourceManager.GetString("connecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تم قطع الإتصال.
        '''</summary>
        Friend Shared ReadOnly Property disconnected() As String
            Get
                Return ResourceManager.GetString("disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to هناك خطأ في النظام , لايمكن تشغيل البرنامج.
        '''</summary>
        Friend Shared ReadOnly Property err_1() As String
            Get
                Return ResourceManager.GetString("err_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to خطأ في الإتصال, بعد 4 محاولات.
        '''</summary>
        Friend Shared ReadOnly Property err_10() As String
            Get
                Return ResourceManager.GetString("err_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لايمكننا التأكد من أن عنوانك قد تغير, ربما اتصالك الانترنت بطيء , بإمكانك التأكد يدوياً, إذا اكتشفت انه لم يتغير , فقط اقطع الاتصال وابحث مجدداً ثم اتصل.
        '''</summary>
        Friend Shared ReadOnly Property err_11() As String
            Get
                Return ResourceManager.GetString("err_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لا يوجد اتصال بالانترنت أو انه بطيء.
        '''</summary>
        Friend Shared ReadOnly Property err_12() As String
            Get
                Return ResourceManager.GetString("err_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to الرجاء اعادة المحاولة.
        '''</summary>
        Friend Shared ReadOnly Property err_2() As String
            Get
                Return ResourceManager.GetString("err_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to الرجاء التأكد من وجود اتصال انترنت لديك وأعد المحاولة (تأكد من الاعدادات -&lt; البروكسي).
        '''</summary>
        Friend Shared ReadOnly Property err_3() As String
            Get
                Return ResourceManager.GetString("err_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعذر انشاء إتصال , الرجاء المحاولة لاحقاً.
        '''</summary>
        Friend Shared ReadOnly Property err_4() As String
            Get
                Return ResourceManager.GetString("err_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعذر الإتصال ابحث مجدداً ثم أعد المحاولة.
        '''</summary>
        Friend Shared ReadOnly Property err_5() As String
            Get
                Return ResourceManager.GetString("err_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تعذر قطع الإتصال.
        '''</summary>
        Friend Shared ReadOnly Property err_6() As String
            Get
                Return ResourceManager.GetString("err_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to الرجاء ملئ الحقول المطلوبة.
        '''</summary>
        Friend Shared ReadOnly Property err_7() As String
            Get
                Return ResourceManager.GetString("err_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لايمكن الحفظ هناك خطأ ما.
        '''</summary>
        Friend Shared ReadOnly Property err_8() As String
            Get
                Return ResourceManager.GetString("err_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to لايمكن جلب الاعدادات.
        '''</summary>
        Friend Shared ReadOnly Property err_9() As String
            Get
                Return ResourceManager.GetString("err_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جار جلب العنوان.
        '''</summary>
        Friend Shared ReadOnly Property get_ip() As String
            Get
                Return ResourceManager.GetString("get_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جار اعادة تثبيت التعاريف.
        '''</summary>
        Friend Shared ReadOnly Property ins_drv() As String
            Get
                Return ResourceManager.GetString("ins_drv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to العنوان الجديد: .
        '''</summary>
        Friend Shared ReadOnly Property new_ip() As String
            Get
                Return ResourceManager.GetString("new_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to كلمة السر.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to المنفذ.
        '''</summary>
        Friend Shared ReadOnly Property port() As String
            Get
                Return ResourceManager.GetString("port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جار تجهيز الملفات.
        '''</summary>
        Friend Shared ReadOnly Property prepare() As String
            Get
                Return ResourceManager.GetString("prepare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to البروكسي.
        '''</summary>
        Friend Shared ReadOnly Property proxy() As String
            Get
                Return ResourceManager.GetString("proxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جاهز للإتصال.
        '''</summary>
        Friend Shared ReadOnly Property ready() As String
            Get
                Return ResourceManager.GetString("ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to العنوان الحقيقي: .
        '''</summary>
        Friend Shared ReadOnly Property real_ip() As String
            Get
                Return ResourceManager.GetString("real_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جار إزالة التعاريف.
        '''</summary>
        Friend Shared ReadOnly Property rem_drv() As String
            Get
                Return ResourceManager.GetString("rem_drv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تم الحفظ.
        '''</summary>
        Friend Shared ReadOnly Property saved() As String
            Get
                Return ResourceManager.GetString("saved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  قوة السيرفر: .
        '''</summary>
        Friend Shared ReadOnly Property server_score() As String
            Get
                Return ResourceManager.GetString("server_score", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to جاري البحث عن سيرفر....
        '''</summary>
        Friend Shared ReadOnly Property server_search() As String
            Get
                Return ResourceManager.GetString("server_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to تم ايقاف الطلب.
        '''</summary>
        Friend Shared ReadOnly Property stopped() As String
            Get
                Return ResourceManager.GetString("stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to اسم المستخدم.
        '''</summary>
        Friend Shared ReadOnly Property username() As String
            Get
                Return ResourceManager.GetString("username", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
