'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class lang_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("unblockDoom.lang_en", GetType(lang_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Done.
        '''</summary>
        Friend Shared ReadOnly Property all_done() As String
            Get
                Return ResourceManager.GetString("all_done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected.
        '''</summary>
        Friend Shared ReadOnly Property connected() As String
            Get
                Return ResourceManager.GetString("connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecting....
        '''</summary>
        Friend Shared ReadOnly Property connecting() As String
            Get
                Return ResourceManager.GetString("connecting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnected.
        '''</summary>
        Friend Shared ReadOnly Property disconnected() As String
            Get
                Return ResourceManager.GetString("disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Error, We Can&apos;t Run Program.
        '''</summary>
        Friend Shared ReadOnly Property err_1() As String
            Get
                Return ResourceManager.GetString("err_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Error, We try 4 times!.
        '''</summary>
        Friend Shared ReadOnly Property err_10() As String
            Get
                Return ResourceManager.GetString("err_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot Determine if Your IP changed, Maybe your connection is too slow. You Can Check it Manualy, if it&apos;s Not changed so try to Disconnect then Search and Connect Again.
        '''</summary>
        Friend Shared ReadOnly Property err_11() As String
            Get
                Return ResourceManager.GetString("err_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No or Slow Internet Connection!!.
        '''</summary>
        Friend Shared ReadOnly Property err_12() As String
            Get
                Return ResourceManager.GetString("err_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Try Again.
        '''</summary>
        Friend Shared ReadOnly Property err_2() As String
            Get
                Return ResourceManager.GetString("err_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Internet Connection, Try Again (Check Setting&gt;Proxy).
        '''</summary>
        Friend Shared ReadOnly Property err_3() As String
            Get
                Return ResourceManager.GetString("err_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We Can&apos;t Connect, Please Try Again.
        '''</summary>
        Friend Shared ReadOnly Property err_4() As String
            Get
                Return ResourceManager.GetString("err_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t Connect, Re-Search and Try Again.
        '''</summary>
        Friend Shared ReadOnly Property err_5() As String
            Get
                Return ResourceManager.GetString("err_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t Disconnect.
        '''</summary>
        Friend Shared ReadOnly Property err_6() As String
            Get
                Return ResourceManager.GetString("err_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Fill All Fields.
        '''</summary>
        Friend Shared ReadOnly Property err_7() As String
            Get
                Return ResourceManager.GetString("err_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t Save, There is Some Error :(.
        '''</summary>
        Friend Shared ReadOnly Property err_8() As String
            Get
                Return ResourceManager.GetString("err_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can&apos;t Retrive Settings.
        '''</summary>
        Friend Shared ReadOnly Property err_9() As String
            Get
                Return ResourceManager.GetString("err_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting IP.
        '''</summary>
        Friend Shared ReadOnly Property get_ip() As String
            Get
                Return ResourceManager.GetString("get_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installing New vLan Driver.
        '''</summary>
        Friend Shared ReadOnly Property ins_drv() As String
            Get
                Return ResourceManager.GetString("ins_drv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to new IP: .
        '''</summary>
        Friend Shared ReadOnly Property new_ip() As String
            Get
                Return ResourceManager.GetString("new_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port.
        '''</summary>
        Friend Shared ReadOnly Property port() As String
            Get
                Return ResourceManager.GetString("port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preparing Files.
        '''</summary>
        Friend Shared ReadOnly Property prepare() As String
            Get
                Return ResourceManager.GetString("prepare", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proxy.
        '''</summary>
        Friend Shared ReadOnly Property proxy() As String
            Get
                Return ResourceManager.GetString("proxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready :).
        '''</summary>
        Friend Shared ReadOnly Property ready() As String
            Get
                Return ResourceManager.GetString("ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to real IP: .
        '''</summary>
        Friend Shared ReadOnly Property real_ip() As String
            Get
                Return ResourceManager.GetString("real_ip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Removing vLan Driver.
        '''</summary>
        Friend Shared ReadOnly Property rem_drv() As String
            Get
                Return ResourceManager.GetString("rem_drv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved.
        '''</summary>
        Friend Shared ReadOnly Property saved() As String
            Get
                Return ResourceManager.GetString("saved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server Score: .
        '''</summary>
        Friend Shared ReadOnly Property server_score() As String
            Get
                Return ResourceManager.GetString("server_score", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching....
        '''</summary>
        Friend Shared ReadOnly Property server_search() As String
            Get
                Return ResourceManager.GetString("server_search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operation Stopped.
        '''</summary>
        Friend Shared ReadOnly Property stopped() As String
            Get
                Return ResourceManager.GetString("stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Friend Shared ReadOnly Property username() As String
            Get
                Return ResourceManager.GetString("username", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
